# Generated by Django 3.0.7 on 2024-02-05 05:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student_management_app', '0006_quiz_quizquestion_quizresult'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quiz',
            name='subject_id',
        ),
        migrations.AddField(
            model_name='subjects',
            name='quizzes',
            field=models.ManyToManyField(blank=True, to='student_management_app.Quiz'),
        ),
    ]
